# main.yml
name: main branch auto ci process script

on: # 아래 job을 실행시킬 상황
  push:
    branches: [main] # main브랜치 푸쉬 받으면 작동

jobs: # 작동할 일
  deploy:
    runs-on: self-hosted # GitHub Actions의 일부로 사용자 정의된 머신으로 self-hosted runner라 불림
    defaults:
      run:
        working-directory: ../..
    steps:
      - name: Move folder and pull remote repository contents
        run: |
          cd /home/ubuntu/iron-mate/
          git pull origin main
          yarn
          pm2 stop all
          yarn build
          pm2 restart all
