# main.yml
name: main branch auto ci process script

on: # 아래 job을 실행시킬 상황
  push:
    branches: [main] # main브랜치 푸쉬 받으면 작동

jobs: # 작동할 일
  deploy:
    runs-on: self-hosted # GitHub Actions의 일부로 사용자 정의된 머신으로 self-hosted runner라 불림
    defaults:
      run:
        working-directory: ../..
    steps: # ec2 내 빌드 시 cpu딸림으로 인해 로컬 빌드 후 푸쉬하는 전략 선택
      - name: Move folder and pull remote repository contents
        run: |
          cd /home/ubuntu/iron-mate/
          pm2 stop all
          git pull origin main
          pm2 restart all
